version: "3.1"
services:
  app:
    image: pixcredbank/tl8emp-astrapay:latest
    networks:
      - xp-production
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
    ports:
      - 5526:80

networks:
  xp-production:
    external: true
