# ------------------------------------------------------------------------
# Manual das Variáveis de Ambiente:
# ------------------------------------------------------------------------
# NODE: Define a versão do Node.js a ser instalada. Exemplo: NODE=21
# PHP: Define a versão do PHP a ser instalada. Exemplo: PHP=8.3
# SWOOLE: Define se a extensão Swoole deve ser instalada. Valores: true/false
# NPM: Define a versão do NPM a ser instalada. Exemplo: NPM=10.5.0
# PORT: Define a porta na qual o Apache irá rodar. Exemplo: PORT=80
# INSTALL_IMAGICK: Define se a extensão Imagick deve ser instalada. Valores: true/false
# DEV: Define se ferramentas adicionais de desenvolvimento devem ser instaladas. Valores: true/false
# SLEEP_TIME: Define o intervalo de tempo em segundos entre cada execução do comando schedule. Exemplo: SLEEP_TIME=60
# UPLOAD_MAX_FILESIZE: Define o tamanho máximo de arquivos para upload no PHP. Exemplo: UPLOAD_MAX_FILESIZE=10M
# POST_MAX_SIZE: Define o tamanho máximo de dados de post no PHP. Exemplo: POST_MAX_SIZE=10M
# MAX_FILE_UPLOADS: Define o número máximo de arquivos para upload no PHP. Exemplo: MAX_FILE_UPLOADS=20
# DISPLAY_ERRORS: Define se os erros devem ser exibidos no PHP. Valores: on/off
# LOG_ERRORS: Define se os erros devem ser logados no PHP. Valores: on/off
# TZ: Define o fuso horário do sistema. Exemplo: TZ=America/Bahia
# ENABLE_SCHEDULE1-5: Define se o comando de schedule correspondente deve ser ativado. Valores: true/false
# SCHEDULE_COMMAND1-5: Define o comando de schedule a ser executado.
# ENABLE_QUEUE1-5: Define se o comando de queue:work correspondente deve ser ativado. Valores: true/false
# QUEUE_COMMAND1-5: Define o comando de queue:work a ser executado.
# ------------------------------------------------------------------------

FROM ubuntu:20.04

# Definicao de versao
ENV NODE=21
ENV PHP=8.3
ENV SWOOLE=false
ENV NPM=10.5.0
ENV PORT=80
ENV INSTALL_IMAGICK=false
ENV DEV=true
ENV SLEEP_TIME=60

# Variáveis de configuração do PHP
ENV UPLOAD_MAX_FILESIZE=10M
ENV POST_MAX_SIZE=10M
ENV MAX_FILE_UPLOADS=20
ENV DISPLAY_ERRORS=on
ENV LOG_ERRORS=on

# Variáveis para ativar/desativar e comandos de schedule
ENV ENABLE_SCHEDULE1=true
ENV SCHEDULE_COMMAND1="php /app/artisan schedule:run"
ENV ENABLE_SCHEDULE2=false
ENV SCHEDULE_COMMAND2=""
ENV ENABLE_SCHEDULE3=false
ENV SCHEDULE_COMMAND3=""
ENV ENABLE_SCHEDULE4=false
ENV SCHEDULE_COMMAND4=""
ENV ENABLE_SCHEDULE5=false
ENV SCHEDULE_COMMAND5=""

# Variáveis para ativar/desativar e comandos de queue:work
ENV ENABLE_QUEUE1=true
ENV QUEUE_COMMAND1="php /app/artisan queue:work"
ENV ENABLE_QUEUE2=false
ENV QUEUE_COMMAND2=""
ENV ENABLE_QUEUE3=false
ENV QUEUE_COMMAND3=""
ENV ENABLE_QUEUE4=false
ENV QUEUE_COMMAND4=""
ENV ENABLE_QUEUE5=false
ENV QUEUE_COMMAND5=""

#################### Sistema Operacional #################################
# Time Zone
ENV TZ=America/Bahia
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

## Install PHP
RUN apt update -y
RUN apt install software-properties-common -y
RUN apt install apache2 -y
RUN apt-get install ca-certificates curl gnupg lsb-release -y
RUN add-apt-repository ppa:ondrej/php -y
RUN apt update -y
RUN apt install php${PHP} php${PHP}-common php${PHP}-mbstring php${PHP}-cli php${PHP}-bcmath php${PHP}-xml php${PHP}-zip php${PHP}-pdo php${PHP}-common php${PHP}-tokenizer php${PHP}-pgsql php${PHP}-curl php${PHP}-gd php${PHP}-pdo php${PHP}-dev php${PHP}-soap -y

## Install IMAGICK (Optional)
RUN if [ "$INSTALL_IMAGICK" = "true" ]; then \
    apt update && \
    apt install -y php${PHP}-imagick && \
    apt install -y imagemagick; \
    fi

## Install dependencias
RUN apt update && \
    apt install git -y &&\
    apt install curl -y && \
    apt install -y tzdata && \
    a2enmod rewrite

### SET ALTERNATIVES
RUN update-alternatives --set php /usr/bin/php${PHP}

### COMPOSER
RUN curl -sS https://getcomposer.org/installer | php && \
    mv composer.phar /usr/local/bin/composer && \
    chmod +x /usr/local/bin/composer

### NODE AND NPM
RUN curl -fsSL https://deb.nodesource.com/setup_${NODE}.x | bash - && \
    apt update && \
    apt install nodejs -y && \
    npm install -g npm@${NPM}

#################### Dependencias #################################

### SWOOLE
RUN if [ "$SWOOLE" = "true" ]; then \
    cd /tmp && git clone https://github.com/swoole/swoole-src.git && \
    cd swoole-src && \
    git checkout v5.1.0 && \
    phpize && \
    ./configure --enable-openssl && \
    make && make install && \
    touch /etc/php/${PHP}/cli/conf.d/swoole.ini && \
    echo 'extension=swoole.so' > /etc/php/${PHP}/cli/conf.d/swoole.ini; \
    fi

### Instalar ferramentas de desenvolvimento adicionais se DEV for true
RUN if [ "$DEV" = "true" ]; then \
    apt update && \
    apt install -y net-tools telnet iputils-ping; \
    fi

########## Configuracoes do APACHE #########
RUN echo "ServerSignature Off" >> /etc/apache2/apache2.conf
RUN echo "ServerTokens Prod" >> /etc/apache2/apache2.conf
RUN echo "TraceEnable off"  >> /etc/apache2/apache2.conf
RUN echo "FileETag None"  >> /etc/apache2/apache2.conf
COPY ./deploy.conf/000-default.conf /etc/apache2/sites-available/
COPY ./deploy.conf/php.ini /etc/php/${PHP}/cli/php.ini

## Configurando as variaveis
WORKDIR /app

COPY . .

COPY env-staging .env

EXPOSE ${PORT}

#ENV COMPOSER_ALLOW_SUPERUSER=1
RUN composer install

RUN touch .env \
    && php artisan key:generate --force

## Montagem da Aplicacao NPM
RUN npm install && npm run build

## Cache routes and config again
RUN php artisan optimize:clear && php artisan optimize

### Fix Permissao
RUN chmod -Rf 777 /app/storage

## Fix Security
RUN rm -Rf /app/deploy.conf && \
    rm -Rf /app/Dockerfile-staging && \
    rm -Rf /app/Dockerfile-production && \
    rm -Rf /app/env-production && \
    rm -Rf /app/env-staging && \
    rm -Rf /app/common_files && \
    rm -Rf /app/.git && \
    rm -Rf /app/.github

### PHP Configuration adjustments
RUN sed -i "s/upload_max_filesize = .*/upload_max_filesize = ${UPLOAD_MAX_FILESIZE}/" /etc/php/${PHP}/cli/php.ini && \
    sed -i "s/post_max_size = .*/post_max_size = ${POST_MAX_SIZE}/" /etc/php/${PHP}/cli/php.ini && \
    sed -i "s/max_file_uploads = .*/max_file_uploads = ${MAX_FILE_UPLOADS}/" /etc/php/${PHP}/cli/php.ini && \
    sed -i "s/display_errors = On/display_errors = ${DISPLAY_ERRORS}/" /etc/php/${PHP}/cli/php.ini && \
    sed -i "s/log_errors = On/log_errors = ${LOG_ERRORS}/" /etc/php/${PHP}/cli/php.ini

# Copy the start script
COPY ./deploy.conf/start.sh /start.sh
RUN chmod +x /start.sh

# Start Apache and Queue with the script
CMD ["/start.sh"]
